version: '3.4'

networks:
  k6:
    external:
      name: k6
      

services:
  k6:
    image: grafana/k6:0.39.0-47-gf2684ad9
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts
